
name: Train and Test Model

on:
  push:
    branches:
      - Raheem
  pull_request:
    branches:
      - Raheem

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Train model
      run: |
        python model.py

    - name: Test model
      run: |
        pytest test.py
